language: node_js
node_js:
  - stable
script:
  - npm run build
  - npm run test
deploy:
  provider: npm
  email: theramin108@gmail.com
  api_key:
    secure: fk3wFDtv8fPXiAY8ke9kYBi1nWH3f7y7WY3EWOYoEWn/en/5vWK1h+zBiHFxVCqmfq2OP9Za4J7wmeuzG2k4ZG0nPWFpUzd5oQpSOYU8JtugZdf+donA7uRBbUiCBVdvNvpZurIAXn63rXfQBkNV3w3jH8VPSWzHpi8R2K3IlJA2cFJU9i+F7RYyvDqmAb4fEo+CK1JF3l2WRiNCfrZz0E4rHDIFQ9zIDdMgMrcEY1GoHDfnkXmqWjJ11cyyg8uqWJCDQ8O3VwmAjV9nA7JYyB/oQS8LhEZfXUKkbSq0MS7pTVB701is8IA4CEmyym4xLlEmZcMTerQRy+GR7WxFIyGwkqll9Yfb0Zcv05GPa5nfOukJ481I/JVXOv3YlQK6kpUCE2CVBAJxTc4dlZzEzk9mhjtWNvmj37bD8cywsEZptp2OoJRR6uIgjUMMUJBHV+EnljVnx7GdQlccTjyjHmOVye/HXcq6yKex5xhBGhfGFh8YRUhb6eDFwiAURR2Bkpu118LwLI7jIqqTBZ4zSThLX5LXonT7LB7O5CbLT6IImxsmaz57W+QuN6BVmkgQc8A96u7VgmyeG44IMtdbi8TXEmZ7kZpGKNxkBi3fH5qFIVqnmNFr5VjOnMl+PEf5a+UFUlk4otmM7uLpJV5yitljxzQCYHMwDK612zGK9XA=
  on:
    branch: production
    repo: Introvertuous/react_native_mqtt
    skip_cleanup: true
